language: node_js
node_js:
- '6.1'
sudo: true
env:
  global:
  - CF_APP=hello-iot
  - CF_API=https://api.cf.us10.hana.ondemand.com
  - CF_USERNAME=piotr.bochynski@hybris.com
  - CF_ORGANIZATION=smartteam
  - CF_SPACE=dev  
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script: cf-blue-green-travis
  on:
    branch: develop
